BEGIN TRANSACTION;
INSERT INTO `orbit_transporter` (id,name) VALUES (1,'Inland Road Transport Pvt Ltd'),
 (2,'ARC Transport'),
 (3,'Amit Transport'),
 (4,'Shree RS Logistics'),
 (5,'Bhagwati Logistics & Transport'),
 (6,'Goods Carrier of India'),
 (7,'Asian transport and logistics'),
 (8,'Relliance Roadways'),
 (9,'Maharastra Cargo'),
 (10,'TCI Freight'),
 (11,'GATI KWE'),
 (13,'NA');
INSERT INTO `orbit_supervision` (id,supervision_scope) VALUES (1,'E&C'),
 (2,'SUPERVISION'),
 (3,'NA');
INSERT INTO `orbit_state` (id,state) VALUES (1,'Andaman and Nicobar Islands'),
 (2,'Andhra Pradesh'),
 (3,'Arunachal Pradesh'),
 (4,'Assam'),
 (5,'Bihar'),
 (6,'Chandigarh'),
 (7,'Chhattisgarh'),
 (8,'Dadra and Nagar Haveli'),
 (9,'Daman and Diu'),
 (10,'Delhi'),
 (11,'Goa'),
 (12,'Gujarat'),
 (13,'Haryana'),
 (14,'Himachal Pradesh'),
 (15,'Jammu and Kashmir'),
 (16,'Jharkhand'),
 (17,'Karnataka'),
 (18,'Kerala'),
 (19,'Lakshadweep'),
 (20,'Madhya Pradesh'),
 (21,'Maharashtra'),
 (22,'Manipur'),
 (23,'Meghalaya'),
 (24,'Mizoram'),
 (25,'Nagaland'),
 (26,'Odisha'),
 (27,'Puducherry'),
 (28,'Punjab'),
 (29,'Rajasthan'),
 (30,'Sikkim'),
 (31,'Tamil Nadu'),
 (32,'Tripura'),
 (33,'Uttar Pradesh'),
 (34,'Uttarakhand'),
 (35,'West Bengal');
INSERT INTO `orbit_salesperson` (id,name) VALUES (1,'Mr. Bikram Bakshi');
INSERT INTO `orbit_productuom` (id,uomProduct) VALUES (1,'NOS'),
 (2,'SET'),
 (3,'KG'),
 (4,'LTR');
INSERT INTO `orbit_ordertype` (id,type) VALUES (1,'DIRECT'),
 (2,'BUY & SELL');
INSERT INTO `orbit_orderstatus` (id,name) VALUES (1,'OPEN'),
 (2,'CLOSED');
INSERT INTO `orbit_orderfileattachment` (id,name) VALUES (1,'Purchase Order'),
 (2,'Cost Sheet'),
 (3,'Final Quotation'),
 (4,'PI Advance Payment'),
 (5,'PI Balance Payment'),
 (6,'Vendor PO'),
 (7,'Principal PO'),
 (8,'GST Invoice'),
 (9,'Packing Slip'),
 (10,'FOC'),
 (12,'Others');
INSERT INTO `orbit_ordercategory` (id,category) VALUES (1,'UNIT'),
 (2,'SPARES'),
 (3,'CHEMICAL'),
 (4,'SERVICE'),
 (5,'SALES_&_SERVICE');
INSERT INTO `orbit_orderbookingstatus` (id,order_booking_status) VALUES (1,'PENDING'),
 (2,'BOOKED');
INSERT INTO `orbit_orderaccount` (id,orderAccount) VALUES (1,'Prerana Engineers & Consultants Pvt Ltd');
INSERT INTO `orbit_localpurchase` (id,name) VALUES (1,'YES'),
 (2,'NO'),
 (3,'NA'),
 (4,'DONE');
INSERT INTO `orbit_industry` (id,industry) VALUES (1,'Agro-based Industries'),
 (2,'Automobiles / Auto Ancillaries'),
 (3,'Beverages'),
 (4,'Brewery / Distillery'),
 (5,'Cement'),
 (6,'Ceramics / Refractories'),
 (7,'Chemicals - Paints & Dyes'),
 (8,'Chemicals - Personal Care'),
 (9,'Chemicals - Polymers & Plastics'),
 (10,'Chemicals - Others'),
 (11,'Defence Establishments'),
 (12,'Drugs & Pharmaceuticals'),
 (13,'Electronics / Communications'),
 (14,'Engineering'),
 (15,'Fertiliser'),
 (16,'Food - Dairy'),
 (17,'Food - Edible Oil Refinery'),
 (18,'Food - Rice'),
 (19,'Food - Sugar'),
 (20,'Food - Tea & Coffee'),
 (21,'Food Processing / Packaged Food'),
 (22,'Food - Others'),
 (23,'Glass / Glass Products'),
 (24,'Hospitality - Hospitals / Clinics'),
 (25,'Hospitality - Hotels / Restaurants / Canteens'),
 (26,'Hospitality - Others'),
 (27,'Infrastructure - Railways'),
 (28,'Infratructure - Roads'),
 (29,'Infratructure - Ports / Airports'),
 (30,'Infrastructure - Others'),
 (31,'Leather / Tannery'),
 (32,'Metals - Iron & Steel'),
 (33,'Metals - Sponge Iron'),
 (34,'Metals - Non-ferrous Metals'),
 (35,'Mining / Minerals'),
 (36,'Oil & Gas - Extraction / Production'),
 (37,'Paper & Packaging'),
 (38,'Power Generation (IPP / Govt)'),
 (39,'Refinery & Petrochemical'),
 (40,'Textiles - Garments'),
 (41,'Textiles - Synthetic Textiles'),
 (42,'Textiles - Textile Processing'),
 (43,'Tobacco'),
 (44,'Tyres / Tubes / Rubber Products'),
 (45,'Urbanisation - Commercial Complex / Malls'),
 (46,'Urbanisation - Housing / Township'),
 (47,'Urbanisation - Educational Institution related'),
 (48,'Urbanisation - SEZs / Industrial or IT Parks'),
 (49,'Urbanisation - Others'),
 (50,'Wood / Plywood / Laminates'),
 (51,'Miscellaneous');
INSERT INTO `orbit_indiatax` (id,tax_rate) VALUES (1,'GST-5%'),
 (2,'GST-12%'),
 (3,'GST-18%');
INSERT INTO `orbit_freightterms` (id,name) VALUES (1,'FOR'),
 (2,'EX-WORKS'),
 (3,'NA');
INSERT INTO `orbit_division` (id,name) VALUES (1,'TMX-HEATING'),
 (2,'TMX-WWS'),
 (3,'TMX-ENVIRO'),
 (4,'TMX-CWSS'),
 (5,'TMX-SSBU'),
 (6,'TMX-FEMS'),
 (7,'TMX-CHEMICAL'),
 (8,'TMX-SOLAR'),
 (9,'TMX-COOLING'),
 (10,'KSB-GGC'),
 (11,'KSB-BALL'),
 (12,'KSB-PUMP'),
 (13,'MIL-VALVE'),
 (14,'DANA-BREVINI-GEARBOX'),
 (15,'DANA-HYDRAULIC-MOTOR'),
 (16,'KAESER-COMPRESSOR');
INSERT INTO `orbit_distatus` (id,name) VALUES (1,'PENDING'),
 (2,'ISSUED'),
 (3,'NA');
INSERT INTO `orbit_deliverystatus` (id,delivery_status) VALUES (1,'PENDING'),
 (2,'PART DELIVERY'),
 (3,'DELIVERED');
INSERT INTO `orbit_commissionstatus` (id,commission_status) VALUES (1,'PENDING'),
 (2,'RECEIVED'),
 (3,'NA');
INSERT INTO `orbit_commissioningstatus` (id,commissioning_status) VALUES (1,'PENDING'),
 (2,'RECEIVED'),
 (3,'NA');
INSERT INTO `orbit_balancestatus` (id,balance_status) VALUES (1,'PENDING'),
 (2,'RECEIVED');
INSERT INTO `orbit_advancestatus` (id,advance_status) VALUES (1,'PENDING'),
 (2,'RECEIVED'),
 (3,'NA');
INSERT INTO `orbit_addresstype` (id,address_type) VALUES (1,'BILLING'),
 (2,'SHIPPING');
INSERT INTO `auth_group` (id,name) VALUES (1,'accounts'),(2,'division'); 
INSERT INTO `auth_group_permissions` (id,group_id,permission_id) VALUES (1,1,128),
 (2,1,129),
 (3,1,132),
 (4,1,140),
 (5,1,21),
 (6,1,24),
 (7,1,28),
 (8,1,32),
 (9,1,36),
 (10,1,37),
 (11,1,40),
 (12,1,44),
 (13,1,48),
 (14,1,49),
 (15,1,52),
 (16,1,56),
 (17,1,60),
 (18,1,64),
 (19,1,68),
 (20,1,72),
 (21,1,76),
 (22,1,80),
 (23,1,81),
 (24,1,84),
 (25,1,88),
 (26,1,92),
 (27,1,96),
 (28,1,100),
 (29,1,104),
 (30,1,108),
 (31,1,112),
 (32,1,116),
 (33,1,120),
 (34,1,121),
 (35,1,124),
 (36,1,125);

COMMIT;
