from django.contrib import admin

from . import models
# Register your models here.
admin.site.register(models.OrderAccount)
admin.site.register(models.Industry)
admin.site.register(models.Account)
admin.site.register(models.AddressType)
admin.site.register(models.Contact)
admin.site.register(models.State)
admin.site.register(models.BillAddress)
admin.site.register(models.ShipAddress)
admin.site.register(models.OrderType)
admin.site.register(models.OrderCategory)
admin.site.register(models.ProductUOM)
admin.site.register(models.IndiaTax)
admin.site.register(models.OrderStatus)
admin.site.register(models.OrderBookingStatus)
admin.site.register(models.AdvanceStatus)
admin.site.register(models.BalanceStatus)
admin.site.register(models.Supervision)
admin.site.register(models.DeliveryStatus)
admin.site.register(models.CommissioningStatus)
admin.site.register(models.CommissionStatus)
admin.site.register(models.Division)
admin.site.register(models.Order)
admin.site.register(models.AccountFile)
admin.site.register(models.OrderFile)
admin.site.register(models.FreightTerms)
admin.site.register(models.DiStatus)
admin.site.register(models.Transporter)
admin.site.register(models.LocalPurchase)
admin.site.register(models.OrderFileAttachment)
admin.site.register(models.SalesPerson)
