# Generated by Django 2.2 on 2020-06-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('app_label', models.CharField(max_length=30)),
                ('object_data', models.CharField(max_length=250)),
                ('content_type', models.CharField(max_length=30)),
                ('action_type', models.CharField(max_length=30)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Histories',
            },
        ),
    ]
