# Generated by Django 2.2 on 2020-06-06 11:03

from django.db import migrations, models
import django.db.models.deletion
import orbit.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('pan', models.CharField(blank=True, max_length=10)),
                ('ph_no', models.CharField(max_length=14)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(help_text='Address Type [ Billing / Shipping ]', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='AdvanceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_status', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_status', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='BillAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=20)),
                ('dist', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=8)),
                ('gst', models.CharField(max_length=15)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.Account')),
                ('address_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.AddressType')),
            ],
        ),
        migrations.CreateModel(
            name='CommissioningStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commissioning_status', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_status', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.Account')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DiStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FreightTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='IndiaTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LocalPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=45, unique=True)),
                ('order_date', models.DateField()),
                ('product_description', models.CharField(help_text='[ Enter brief description about product ]', max_length=255)),
                ('qty', models.IntegerField()),
                ('amount', models.FloatField()),
                ('so_no', models.CharField(blank=True, help_text='[ SO Number from Principal Company ]', max_length=40, null=True)),
                ('payment_terms', models.CharField(max_length=255)),
                ('advance_amount', models.FloatField()),
                ('balance_amount', models.FloatField()),
                ('delivery_date', models.DateField()),
                ('local_purchase_required_date', models.DateField(blank=True, null=True)),
                ('di_date', models.DateField(blank=True, null=True)),
                ('commissioning_amount', models.FloatField(blank=True, help_text='[ Pending payments for site commissioning ]', null=True)),
                ('commission_amount', models.FloatField(blank=True, help_text='[ Commision are yet to receive from Principal Company for this order ]', null=True)),
                ('remarks', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.Account')),
                ('advance_status', models.ForeignKey(help_text='[ ABG / Advance Recived? ]', on_delete=django.db.models.deletion.CASCADE, to='orbit.AdvanceStatus')),
                ('balance_status', models.ForeignKey(help_text='[ PBG / Balance Received? ]', on_delete=django.db.models.deletion.CASCADE, to='orbit.BalanceStatus')),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.BillAddress')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderAccount', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBookingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_booking_status', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFileAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProductUOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uomProduct', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(help_text='Indian State', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervision_scope', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ShipAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=20)),
                ('dist', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=8)),
                ('gst', models.CharField(max_length=15)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.Account')),
                ('address_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.AddressType')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.State')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', validators=[orbit.validators.validate_file_extension, orbit.validators.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.Order')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.OrderFileAttachment')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.OrderCategory'),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.CommissionStatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='commissioning_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.CommissioningStatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.Contact'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.DeliveryStatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='di_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orbit.DiStatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.Division'),
        ),
        migrations.AddField(
            model_name='order',
            name='freight_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orbit.FreightTerms'),
        ),
        migrations.AddField(
            model_name='order',
            name='local_purchase_required',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.LocalPurchase'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.OrderAccount'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_booking_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.OrderBookingStatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.OrderStatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.OrderType'),
        ),
        migrations.AddField(
            model_name='order',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orbit.SalesPerson'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.ShipAddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='supervision_scope',
            field=models.ForeignKey(help_text='[ Supervision / E&C Scope ]', on_delete=django.db.models.deletion.CASCADE, to='orbit.Supervision'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.IndiaTax'),
        ),
        migrations.AddField(
            model_name='order',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orbit.Transporter'),
        ),
        migrations.AddField(
            model_name='order',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.ProductUOM'),
        ),
        migrations.AddField(
            model_name='billaddress',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.State'),
        ),
        migrations.CreateModel(
            name='AccountFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orbit.Industry'),
        ),
    ]
