# Generated by Django 2.2 on 2020-03-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0002_auto_20200305_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
