# Generated by Django 2.2 on 2020-06-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0002_auto_20200606_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='industry',
            field=models.CharField(max_length=60),
        ),
    ]
