# Generated by Django 2.2 on 2020-03-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0003_auto_20200305_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='uin',
            new_name='pan',
        ),
    ]
