# Generated by Django 2.2 on 2020-03-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0004_auto_20200305_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pan',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
