# Generated by Django 2.2 on 2020-03-26 11:25

from django.db import migrations, models
import orbit.validators


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0005_auto_20200326_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfile',
            name='file',
            field=models.FileField(upload_to='', validators=[orbit.validators.validate_file_size, orbit.validators.validate_file_extension]),
        ),
    ]
