# Generated by Django 2.2 on 2020-03-26 11:32

from django.db import migrations, models
import orbit.validators


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0006_auto_20200326_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfile',
            name='file',
            field=models.FileField(upload_to='', validators=[orbit.validators.validate_file_extension, orbit.validators.validate_file_size]),
        ),
    ]
